	program implied

		implicit none
		integer :: a,i,b
		
		! Outputs values from 1 to 100.
		write(*,*) "Implied do test: ", (/(a,a=1,100)/)
		
		! It is possible to use an implied do in place of an array.
		a=sum((/(i,i=1,100)/))
		write(*,*) "Summation of values generated by an impled do: ", a

		! Can we take the dot product of two implied do loops?
		b=dot_product((/(i,i=1,100)/),(/(a,a=1,100)/))

		write(*,*) "Result of dot product of two implied do loops: ", b
		
		
	end program implied
	