	program implied

		implicit none
		integer :: a,i,b
		integer, dimension(100):: c
		
		! Outputs values from 1 to 100.
		write(*,*) "Implied do test: ", (/(a,a=1,100)/)
		
		! It is possible to use an implied do in place of an array.
		a=sum((/(i,i=1,100)/))
		write(*,*) "Summation of values generated by an impled do: ", a

		! Can we take the dot product of two implied do loops?
		b=dot_product((/(i,i=1,100)/),(/(a,a=1,100)/))

		write(*,*) "Result of dot product of two implied do loops: ", b
		
		! Let's try multiplying two implied do loops...
		c=(/(a,a=1,100)/)*(/(i, i=1, 100)/)
		write(*,*) "Result of multiplying two implied do loops:", c
		
		! Fascinating! Rasing to a power?
		!c=(/(a,a=1,100)/)**(/(i, i=1, 100)/)
		!write(*,*) "Raising implied do to the power of an implied do: ", c
		! Hmm, doesn't like that. Says they are incommensurate.
		
	end program implied
	